insert into carro (id, marca, modelo, ano) values (51, 'Chevrolet', 'Sportvan G20', 1995);
insert into carro (id, marca, modelo, ano) values (52, 'Chevrolet', 'Impala', 2006);
insert into carro (id, marca, modelo, ano) values (53, 'Audi', 'V8', 1992);
insert into carro (id, marca, modelo, ano) values (54, 'Plymouth', 'Acclaim', 1992);
insert into carro (id, marca, modelo, ano) values (55, 'Nissan', 'Armada', 2009);
insert into carro (id, marca, modelo, ano) values (56, 'Lexus', 'SC', 2002);
insert into carro (id, marca, modelo, ano) values (57, 'Toyota', '4Runner', 2002);
insert into carro (id, marca, modelo, ano) values (58, 'Ford', 'Explorer Sport Trac', 2006);
insert into carro (id, marca, modelo, ano) values (59, 'Cadillac', 'DeVille', 1993);
insert into carro (id, marca, modelo, ano) values (60, 'Honda', 'Civic', 1989);
insert into carro (id, marca, modelo, ano) values (61, 'Buick', 'Coachbuilder', 1995);
insert into carro (id, marca, modelo, ano) values (62, 'Lamborghini', 'Diablo', 1997);
insert into carro (id, marca, modelo, ano) values (63, 'Audi', 'S4', 2008);
insert into carro (id, marca, modelo, ano) values (64, 'Toyota', 'Land Cruiser', 2006);
insert into carro (id, marca, modelo, ano) values (65, 'Hyundai', 'Tiburon', 2008);
insert into carro (id, marca, modelo, ano) values (66, 'Chevrolet', 'Tracker', 2003);
insert into carro (id, marca, modelo, ano) values (67, 'Pontiac', 'Parisienne', 1986);
insert into carro (id, marca, modelo, ano) values (68, 'Ford', 'Econoline E250', 1995);
insert into carro (id, marca, modelo, ano) values (69, 'Ford', 'Crown Victoria', 1996);
insert into carro (id, marca, modelo, ano) values (70, 'Volkswagen', 'Cabriolet', 1987);
insert into carro (id, marca, modelo, ano) values (71, 'Nissan', 'Frontier', 1998);
insert into carro (id, marca, modelo, ano) values (72, 'Dodge', 'Ram Van 1500', 1998);
insert into carro (id, marca, modelo, ano) values (73, 'Volkswagen', 'Golf', 1988);
insert into carro (id, marca, modelo, ano) values (74, 'GMC', 'Sierra 1500', 2012);
insert into carro (id, marca, modelo, ano) values (75, 'Austin', 'Mini Cooper', 1961);
insert into carro (id, marca, modelo, ano) values (76, 'Lexus', 'ES', 2007);
insert into carro (id, marca, modelo, ano) values (77, 'Subaru', 'Impreza', 2012);
insert into carro (id, marca, modelo, ano) values (78, 'Toyota', '4Runner', 1992);
insert into carro (id, marca, modelo, ano) values (79, 'Honda', 'Element', 2005);
insert into carro (id, marca, modelo, ano) values (80, 'Chrysler', 'Voyager', 2001);
insert into carro (id, marca, modelo, ano) values (81, 'Plymouth', 'Voyager', 1998);
insert into carro (id, marca, modelo, ano) values (82, 'Volkswagen', 'Eurovan', 2000);
insert into carro (id, marca, modelo, ano) values (83, 'Jaguar', 'X-Type', 2005);
insert into carro (id, marca, modelo, ano) values (84, 'Dodge', 'Neon', 1998);
insert into carro (id, marca, modelo, ano) values (85, 'Toyota', 'Solara', 2001);
insert into carro (id, marca, modelo, ano) values (86, 'Volvo', 'XC60', 2009);
insert into carro (id, marca, modelo, ano) values (87, 'Mercury', 'Monterey', 2007);
insert into carro (id, marca, modelo, ano) values (88, 'Rolls-Royce', 'Phantom', 2005);
insert into carro (id, marca, modelo, ano) values (89, 'Land Rover', 'Discovery Series II', 2001);
insert into carro (id, marca, modelo, ano) values (90, 'GMC', 'Envoy', 2009);
insert into carro (id, marca, modelo, ano) values (91, 'Cadillac', 'Eldorado', 1994);
insert into carro (id, marca, modelo, ano) values (92, 'Audi', 'S6', 1995);
insert into carro (id, marca, modelo, ano) values (93, 'Mercedes-Benz', 'S-Class', 1994);
insert into carro (id, marca, modelo, ano) values (94, 'Audi', '5000S', 1987);
insert into carro (id, marca, modelo, ano) values (95, 'Suzuki', 'Verona', 2005);
insert into carro (id, marca, modelo, ano) values (96, 'Toyota', 'Tacoma', 2005);
insert into carro (id, marca, modelo, ano) values (97, 'Hyundai', 'Santa Fe', 2003);
insert into carro (id, marca, modelo, ano) values (98, 'Pontiac', 'GTO', 2006);
insert into carro (id, marca, modelo, ano) values (99, 'Buick', 'Estate', 1990);
insert into carro (id, marca, modelo, ano) values (100, 'BMW', '530', 2006);
