insert into carro (id, marca, modelo, ano, usuario_id) values (1, 'Ferrari', 'F430', 2006, 6);
insert into carro (id, marca, modelo, ano, usuario_id) values (2, 'Pontiac', 'Firefly', 1988, 8);
insert into carro (id, marca, modelo, ano, usuario_id) values (3, 'Infiniti', 'Q', 1994, 3);
insert into carro (id, marca, modelo, ano, usuario_id) values (4, 'Chrysler', 'Crossfire', 2004, 4);
insert into carro (id, marca, modelo, ano, usuario_id) values (5, 'Mercedes-Benz', 'E-Class', 1995, 8);
insert into carro (id, marca, modelo, ano, usuario_id) values (6, 'Volkswagen', 'Jetta', 1986, 4);
insert into carro (id, marca, modelo, ano, usuario_id) values (7, 'Suzuki', 'SJ 410', 1984, 4);
insert into carro (id, marca, modelo, ano, usuario_id) values (8, 'Suzuki', 'Vitara', 1999, 10);
insert into carro (id, marca, modelo, ano, usuario_id) values (9, 'Saturn', 'Outlook', 2007, 8);
insert into carro (id, marca, modelo, ano, usuario_id) values (10, 'Honda', 'Civic', 1996, 8);
insert into carro (id, marca, modelo, ano, usuario_id) values (11, 'Honda', 'CR-Z', 2011, 7);
insert into carro (id, marca, modelo, ano, usuario_id) values (12, 'Nissan', 'Altima', 1997, 8);
insert into carro (id, marca, modelo, ano, usuario_id) values (13, 'Daewoo', 'Lanos', 1999, 4);
insert into carro (id, marca, modelo, ano, usuario_id) values (14, 'Volvo', 'V50', 2006, 6);
insert into carro (id, marca, modelo, ano, usuario_id) values (15, 'Ford', 'F150', 1984, 1);
insert into carro (id, marca, modelo, ano, usuario_id) values (16, 'Mitsubishi', 'Endeavor', 2007, 4);
insert into carro (id, marca, modelo, ano, usuario_id) values (17, 'Chevrolet', 'Impala', 2011, 2);
insert into carro (id, marca, modelo, ano, usuario_id) values (18, 'Dodge', 'Charger', 1969, 3);
insert into carro (id, marca, modelo, ano, usuario_id) values (19, 'Ford', 'F250', 2010, 3);
insert into carro (id, marca, modelo, ano, usuario_id) values (20, 'Lexus', 'RX', 2012, 3);
insert into carro (id, marca, modelo, ano, usuario_id) values (21, 'Mercury', 'Montego', 2007, 3);
insert into carro (id, marca, modelo, ano, usuario_id) values (22, 'Mercedes-Benz', 'C-Class', 2004, 2);
insert into carro (id, marca, modelo, ano, usuario_id) values (23, 'BMW', '7 Series', 1996, 8);
insert into carro (id, marca, modelo, ano, usuario_id) values (24, 'Pontiac', 'Grand Prix', 2002, 6);
insert into carro (id, marca, modelo, ano, usuario_id) values (25, 'Volkswagen', 'Jetta', 1996, 10);
insert into carro (id, marca, modelo, ano, usuario_id) values (26, 'Maserati', 'GranTurismo', 2012, 4);
insert into carro (id, marca, modelo, ano, usuario_id) values (27, 'Acura', 'SLX', 1997, 6);
insert into carro (id, marca, modelo, ano, usuario_id) values (28, 'Cadillac', 'SRX', 2010, 2);
insert into carro (id, marca, modelo, ano, usuario_id) values (29, 'Ford', 'Expedition EL', 2012, 1);
insert into carro (id, marca, modelo, ano, usuario_id) values (30, 'Pontiac', 'Grand Prix', 2005, 3);
insert into carro (id, marca, modelo, ano, usuario_id) values (31, 'Chrysler', 'Aspen', 2007, 10);
insert into carro (id, marca, modelo, ano, usuario_id) values (32, 'Audi', 'A4', 2003, 6);
insert into carro (id, marca, modelo, ano, usuario_id) values (33, 'Land Rover', 'Discovery', 2006, 10);
insert into carro (id, marca, modelo, ano, usuario_id) values (34, 'Maserati', 'Biturbo', 1986, 8);
insert into carro (id, marca, modelo, ano, usuario_id) values (35, 'Toyota', '4Runner', 1993, 6);
insert into carro (id, marca, modelo, ano, usuario_id) values (36, 'Mazda', 'MX-6', 1993, 4);
insert into carro (id, marca, modelo, ano, usuario_id) values (37, 'Toyota', 'Land Cruiser', 2005, 4);
insert into carro (id, marca, modelo, ano, usuario_id) values (38, 'Lincoln', 'Continental', 1996, 6);
insert into carro (id, marca, modelo, ano, usuario_id) values (39, 'Ford', 'Explorer', 2013, 4);
insert into carro (id, marca, modelo, ano, usuario_id) values (40, 'Dodge', 'Ram Van 1500', 1997, 5);
insert into carro (id, marca, modelo, ano, usuario_id) values (41, 'Ford', 'Econoline E350', 2001, 3);
insert into carro (id, marca, modelo, ano, usuario_id) values (42, 'BMW', 'Z4 M Roadster', 2009, 5);
insert into carro (id, marca, modelo, ano, usuario_id) values (43, 'Toyota', 'Corolla', 1997, 7);
insert into carro (id, marca, modelo, ano, usuario_id) values (44, 'Mazda', 'Mazdaspeed 3', 2007, 10);
insert into carro (id, marca, modelo, ano, usuario_id) values (45, 'Mercury', 'Grand Marquis', 2008, 7);
insert into carro (id, marca, modelo, ano, usuario_id) values (46, 'Ford', 'E-Series', 2008, 2);
insert into carro (id, marca, modelo, ano, usuario_id) values (47, 'Cadillac', 'XLR', 2004, 1);
insert into carro (id, marca, modelo, ano, usuario_id) values (48, 'Suzuki', 'Swift', 1991, 6);
insert into carro (id, marca, modelo, ano, usuario_id) values (49, 'Cadillac', 'Catera', 1999, 9);
insert into carro (id, marca, modelo, ano, usuario_id) values (50, 'Mazda', 'Tribute', 2010, 7);
